### PR TITLE
effects clear on kit change

### PR DESCRIPTION
**Pull request by artulloss**
good if they have more than one kit per life

### CODE REVIEW

**Comment by NidPlays** [comment]
I would recommend adding an option on the config file

**Comment by artulloss** [comment]
true but u really want people stacking effects if multiple kits per life is enabled?

**Comment by DeadOnBushPH** [comment]
How can i add kit?

**Comment by NidPlays** [comment]
That's why you add a config people can decide on their own

**Comment by artulloss** [comment]
Yea alright kind of busy rn I'll add it in a few days.

**Comment by Infernus101** [comment]
Add a config option for this.

**Comment by artulloss** [comment]
added config

**Pull request merged**
